### ISSUE TITLE
cmake version dependency too strict

### ISSUE THREAD

**Issue by sriemer** [interkosmos/xroach#1]
https://github.com/interkosmos/xroach/blob/c0ef65c9cb7b7f3662fbcff837ee95ce4c2e35b2/CMakeLists.txt#L1

cmake 3.5.2 on openSUSE Leap 42.3 released end of last year is able to put this together. After installing `libX11-devel` it is happy. The depend can be lowered at least to version 3.5. Please think about backward compatibility for still supported Linux distributions.

**Comment by interkosmos** [comment]
Changed CMake minimum version to 3.5.
