### ISSUE TITLE
README: cmake uses C++ compiler by default

### ISSUE THREAD

**Issue by sriemer** [interkosmos/xroach#2]
If the C++ compiler is not installed, then `cmake` complains about the missing CXX environment variable.

The solution is to tell cmake that the C++ compiler is gcc (the C compiler).

```
CXX=gcc cmake .
```

**Comment by interkosmos** [comment]
So, you have an C compiler installed, but no C++?

**Comment by sriemer** [comment]
Exactly. Fresh Leap 42.3 VM to test stuff. For C I usually only need `gcc` and not `gcc-c++` as well.
It is a known problem that `cmake` is always looking for a C++ compiler.

**Comment by interkosmos** [comment]
Those weird Linux chaps. Updated the README.

**Comment by sriemer** [comment]
This might be the reason why C tools usually use the autotools.

**Comment by interkosmos** [comment]
But these are not common outside the Linux world ([see](http://www.openbsd.org/images/hackathons/p2k12-s.gif)).
