### ISSUE TITLE
xroach for gnome etc..

### ISSUE THREAD

**Issue by wvermin** [interkosmos/xroach#3]
Hi Philipp,

as you can see here: https://sourceforge.net/projects/xsnow/ and and here: https://sourceforge.net/projects/xpenguins/ , I managed to convert xsnow and xpenguins to run in desktops like gnome and kde. The original versions ran only in fvwm-like desktops.

As you know, xroach will not produce visible roaches on desktops like gnome and kde. That is a pity, and I am planning to convert xroach in the same way as I did with xsnow and xpenguins.

If you agree, what do you think it is the best way to proceed? 

- a fork of your github project
- a new project in sourceforge, with perhaps another name like xrouch-ng
- something else

Regards,

Willem
website: https://www.ratrabbit.nl/ratrabbit/index.html

**Comment by interkosmos** [comment]
I have no concerns whatsoever, especially, as I’m not the original author (and therefore, not the copyright holder). I’m afraid the choice of a name is totally up to you. :smiley: And because SourceForge is dead/dying, I can just give the advice to simply fork the project.
